/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'physi' at '7/25/16 10:56 PM' with Gradle 2.14
 *
 * @author physi, @date 7/25/16 10:56 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
